# Generated by Django 4.2.17 on 2024-12-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='claimed_by',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
