# Generated by Django 4.2.17 on 2025-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_request_claimed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
