# Generated by Django 4.2.17 on 2025-01-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
